# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="robbyrussell"

# Global aliases
alias zshconfig="vim ~/.zshrc"
alias ohmyzsh="vim ~/.oh-my-zsh"
alias machine="docker-machine"
alias compose="docker-compose"

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git golang brew heroku node docker docker-compose docker-machine docker-swarm npm node)

source $ZSH/oh-my-zsh.sh
# Disable auto correct
unsetopt correct_all

export GOPATH=$HOME/code/go
export GOROOT=/usr/local/opt/go/libexec
export GOCODE=$GOPATH/src/github.com/ghigt
export PATH=$GOPATH/bin:$GOROOT/bin:$PATH

export EDITOR='vim'
export DISABLE_AUTO_TITLE=true

## z configuration
. `brew --prefix`/etc/profile.d/z.sh
